### ISSUE TITLE
Change -Path to -LiteralPath in Move-Item to support filenames with []-brackets

### ISSUE THREAD

**Issue by 1110101** [deadlydog/MoveFilesIntoDateDirectories#2]
Hi and thanks for sharing your script with the public!

I had some files with []-brackets in the filename.
The solution seems to be to use -LiteralPath instead of -Path: https://stackoverflow.com/questions/66979845/move-item-not-working-with-some-file-names

It works locally for me, it might be a worthy improvement.

https://github.com/deadlydog/MoveFilesIntoDateDirectories/blob/e8bf96cd3e0c403ec4da575e1f4b5dfb6e9669a0/src/MoveFilesIntoDateDirectories.ps1#L42

**Comment by deadlydog** [comment]
Thanks for the suggestion. I've released v1.1.0 of the script to address this issue. If you still have any issues let me know. Thanks!
