### ISSUE TITLE
How to exclude specific file types?

### ISSUE THREAD

**Issue by deadlydog** [deadlydog/MoveFilesIntoDateDirectories#8]
Question from email:

> Hi Daniel,
> 
> I'm a complete beginner when it comes to powershell, but your script 'MoveFilesIntoDateDirectories' is almost perfect for me.
> My only problem, I still have files in my directory that I don't want to copy.
> Is it possible or in what way could it be possible to define only a certain file type in the script?
> 
> I'm also not sure how I could have put this request in Github.
> Thank you very much for a possible answer and above all thank you for the script/good work.
> 
> Regards
> 
> Uwe

**Comment by deadlydog** [comment]
Currently, there are no parameters to allow excluding specific file types.

What you can do though is modify [this line](https://github.com/deadlydog/MoveFilesIntoDateDirectories/blob/e10a54e08d41ca8d51da1da6f63b0b26f0a954c6/src/MoveFilesIntoDateDirectories.psm1#L45) to update the `Get-ChildItem` command to use the [-Exclude parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.4#example-5-get-child-items-using-the-exclude-parameter) to ignore the file types you do not want included. I hope that helps.

I haven't worked on this module in quite a while, but will make a note for this to be a potential feature on a future version. Thanks!

**Comment by uweban** [comment]
Of course I have expressed myself in an unnecessarily complicated way. I don't necessarily want to exclude file types, but rather only move certain file types, as there are different types in the directory. 

I have been searching all morning and have found the following solution that works for me.

`$filesToMove = Get-ChildItem -Path $SourceDirectoryPath -File -Force | Where-Object { $_.Name -like '*.log.gz' }`

But thanks again for your Script, it helped alot, especially for learning about the topic.
Uwe

**Comment by deadlydog** [comment]
Awesome, I'm glad you got it working 🙂

An alternative approach would be to use [the -Include parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.4#example-4-get-child-items-using-the-include-parameter), like this:

```
$filesToMove = Get-ChildItem -Path $SourceDirectoryPath -File -Force -Include '*.log.gz'
```

Either way will work though. Cheers!
